server:
  port: 8080
spring:
  application:
    name: blog
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 本地数据库
      url: 
      username: 
      # 数据库密码
      password: 
      db-type: com.alibaba.druid.pool.DruidDataSource
      test-on-borrow: true
      test-while-idle: true
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    host: inadvertently.top
    port: 6379
    password: 2539195984
    connect-timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto


# 需要配置阿里云oss 上传 否则无法上传图片功能
aliyun:
  oss:
    file:
      endpoint: 
      keyid: 
      keysecret: 
      bucketname: 

# MD5 加密盐
blog:
  Md5Salt: 

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 86400
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false




